apiVersion : networking.k8s.io/v1
kind : Ingress
metadata :
  name : datacom
  annotations :
    kubernetes.io/ingress.class : nginx
    nginx.ingress.kubernetes.io/rewrite-target : /
spec :
  rules :
  - host : http://datac.australiaeast.cloudapp.azure.com/
    http :
      paths :
      - path : /
        backend :
          serviceName : datacom
          servicePort : 3000