apiVersion : extensions/v1beta1
kind : Ingress
metadata :
  name : datacom
  annotations :
    kubernetes.io/ingress.class : nginx
    nginx.ingress.kubernetes.io/rewrite-target : /
spec :
  rules :
  - host : 20.40.125.208
    http :
      paths :
      - path : /
        backend :
          serviceName : datacom
          servicePort : 3000