name: Unit Testing with Jest

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  buildAndTest:
    name: Unit Testing in Jest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Install dependencies
        run: npm install
      - run: npm run build -- if-present
      - run: npm test
  
  
  sonarCloudTrigger:
      needs: buildAndTest
      name: SonarCloud Trigger
      runs-on: ubuntu-latest
      steps:
        - name: Clone Repo
          uses: actions/checkout@v2
        - name: Analyse with SonarCloud
          uses: sonarsource/sonarcloud-github-action@v1.3
          env:
            GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  
  
  dockerBuild:
      needs: sonarCloudTrigger
      runs-on: ubuntu-latest
      
      steps:
      
        - name: Check Out Repo 
          uses: actions/checkout@v2

        - name: Login to Docker Hub
          uses: docker/login-action@v1
          with:
            username: ${{ secrets.DOCKER_HUB_USERNAME }}
            password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

        - name: Set up Docker Buildx
          id: buildx
          uses: docker/setup-buildx-action@v1

        - name: Build and push
          id: docker_build
          uses: docker/build-push-action@v2
          with:
            context: ./
            file: ./Dockerfile
            push: true
            tags: ${{ secrets.DOCKER_HUB_USERNAME }}/dc_app:latest

        - name: Image digest
          run: echo ${{ steps.docker_build.outputs.digest }}